### ISSUE TITLE
공유하기 사진 테스트

### ISSUE THREAD

**Issue by WooWan** [Nexters/invi#4]
![Inbi Bee](https://github.com/user-attachments/assets/aea7c5d9-bb8b-4895-9aa8-2552154ba8d4)

**Comment by bepyan** [comment]
<img width="196" alt="Frame 48098085 (2)" src="https://github.com/user-attachments/assets/b4b74497-1db9-4c95-a52f-959558fb804a">
<img width="196" alt="Frame 48098085 (1)" src="https://github.com/user-attachments/assets/2a48140e-b658-458d-b4aa-3a1222d0ea42">
<img width="196" alt="Frame 48098100" src="https://github.com/user-attachments/assets/e9fb92f4-9f6c-4cb3-8a3e-0baf050c559b">
<img width="196" alt="Frame 48098085" src="https://github.com/user-attachments/assets/065006f4-37ca-40d0-8c3f-b6eeb0dd5121">
